# 导入所有你可能用到的组件类

import os
import sys
# 添加项目根目录到 Python 路径
current_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_dir)
if project_root not in sys.path:
    sys.path.insert(0, project_root)
from src.dataset.pointodyssey import PointOdysseyDataset_P1,PointOdysseyDataset_P2,PointOdysseyDataset_P3,PointOdysseyDataset_P4
from src.dataset.primitives_v0 import PrimitivesDataset_v0
from src.dataset.primitives_v1 import PrimitivesDataset_v1_albedo_using_basecolor as PrimitivesDataset_v1
from src.dataset.primitives_v1_caption import PrimitivesDataset_v1_albedo_using_basecolor as PrimitivesDataset_v1_Caption
from src.dataset.interiorverse import InteriorverseSingleFrame
from src.dataset.interiorverse_caption import InteriorverseSingleFrame as InteriorverseSingleFrame_Caption
from src.dataset.interiorverse_caption_tonemap_only_from_embedding import InteriorverseSingleFrame as InteriorverseSingleFrame_Caption_Tonemap_Only_From_Embedding
from src.dataset.interiorverse_tonemap import InteriorverseSingleFrame as InteriorverseSingleFrame_Tonemap
from src.dataset.interiorverse_caption_tonemap import InteriorverseSingleFrame as InteriorverseSingleFrame_Caption_Tonemap
from src.dataset.in_the_wild import InTheWildVideoDataset
from src.dataset.in_the_wild_intrinsix import InTheWildIntrinsixDataset
from src.dataset.in_the_wild_intrinsix_v1 import InTheWildIntrinsixDataset as InTheWildIntrinsixDataset_v1
from src.dataset.psmix import PSMix
from src.dataset.psverse import PSVerse
from src.dataset.ibims import IBIMSDataset
from src.dataset.nyuv2 import NYU2Dataset
from src.dataset.sintel import SintelDataset
from src.dataset.scannet import ScanNetDataset
try:
    from src.dataset.hypersim import HypersimDataset
except ImportError:
    HypersimDataset = None  # h5py not installed
from src.dataset.videomatte240k import VideoMatte240KDataset
from src.dataset.multiscene360 import MultiScene360Dataset
from src.dataset.openhumanvid_flare import OpenHumanVidFlareDataset
from src.dataset.videomatte240k_test import VideoMatte240KTestDataset
from src.dataset.videomatte240k_v2 import VideoMatte240KDataset as VideoMatte240KDataset_v2
from src.dataset.videomatte240k_background import VideoMatte240KDataset as VideoMatte240KDataset_inference_background_generation
from src.dataset.flare_video import FlareVideoDataset
from src.dataset.openhumanvid_flare_evaluate import OpenHumanVidFlareEval
from src.dataset.matte_footage import MatteFootageDataset
from src.dataset.ourpbrdata import OurPBRData
from src.dataset.ourpbrdata_crop import OurPBRData as OurPBRData_Crop
from src.dataset.sintel_crop import SintelDataset as SintelDataset_Crop
from src.dataset.sintel_debug import SintelDataset as SintelDataset_Debug
from src.dataset.interiorverse_caption_tonemap_inference import InteriorverseSingleFrame as InteriorverseSingleFrame_Caption_Tonemap_Inference
from src.dataset.interiorverse_caption_tonemap_train import InteriorverseSingleFrame as InteriorverseSingleFrame_Caption_Tonemap_Train
from src.dataset.hypersim_clean import HypersimDataset as HypersimDataset_Clean
from src.dataset.interiorverse_caption_tonemap_train_new import Interiorverse as Interiorverse_Caption_Tonemap_Train_New
from src.dataset.ourpbrdata_crop_eval import OurPBRData as OurPBRData_Crop_Eval
from src.dataset.hypersim_test import HypersimDataset as HypersimDataset_Test
from src.dataset.hypersim_test_clean import HypersimDataset as HypersimDataset_Test_Clean
from src.dataset.youtubematte_test import YoutubeMatteTestDataset
from src.dataset.ourpbrdata_newdata import OurPBRData as OurPBRData_New
from src.dataset.in_the_wild_for_pbr import InTheWildVideoDataset as InTheWildVideoDataset_For_PBR
from src.dataset.in_the_wild_images import InTheWildImageDataset as InTheWildImageDataset_For_PBR
from src.dataset.ourpbrdata_crop_eval_for_demo import OurPBRData as OurPBRData_Crop_Eval_For_Demo
from src.trainers.IR_depth_normal_trainer_v0 import ModelCheckpointCallback_IR_depth_normal_v0,WanTrainingModule_IR_depth_normal_v0,TensorboardLoggingCallback_IR_depth_normal_v0
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR

from src.dataset.basic import VideoDataset #最基础的

from src.trainers.wan2_1_fun_14b_control_normal_lora_train_po_v0 import WanTrainingModule_wan2_1_fun_14b_control_normal_lora_train_po_v0
from src.trainers.wan2_1_fun_14b_control_normal_lora_train_po_v0 import ModelCheckpointCallback_wan2_1_fun_14b_control_normal_lora_train_po_v0,TensorboardLoggingCallback_wan2_1_fun_14b_control_normal_lora_train_po_v0
from src.trainers.wan2_1_fun_14b_control_normal_lora_train_po_v0 import Trainer_wan2_1_fun_14b_control_normal_lora_train_po_v0
from src.trainers.wan2_1_fun_1_3b_control_normal_lora_train_po_v0 import WanTrainingModule_wan2_1_fun_1_3b_control_normal_lora_train_po_v0
from src.trainers.wan2_1_fun_1_3b_control_normal_lora_train_po_v0 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_lora_train_po_v0,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_lora_train_po_v0
from src.trainers.wan2_1_fun_1_3b_control_normal_lora_train_po_v0 import Trainer_wan2_1_fun_1_3b_control_normal_lora_train_po_v0
from src.trainers.wan2_1_t2v_1_3b_control_normal_train_po_v0 import ModelCheckpointCallback_wan2_1_t2v_1_3b_control_normal_train_po_v0,TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_train_po_v0
from src.trainers.wan2_1_t2v_1_3b_control_normal_train_po_v0 import Trainer_wan2_1_t2v_1_3b_control_normal_train_po_v0 
from src.pipelines.wan2_1_t2v_1_3b_control_normal_train_v0 import WanTrainingModule_wan2_1_t2v_1_3b_control_normal_train_po_v0
from src.trainers.wan2_1_t2v_1_3b_control_normal_lora_train_po_v0 import ModelCheckpointCallback_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0,TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0
from src.trainers.wan2_1_t2v_1_3b_control_normal_lora_train_po_v0 import Trainer_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0
from src.pipelines.wan2_1_t2v_1_3b_control_normal_lora_train_v0 import WanTrainingModule_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0
from src.trainers.wan2_1_t2v_1_3b_control_normal_depth_train_po_v1 import ModelCheckpointCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1,TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1
from src.trainers.wan2_1_t2v_1_3b_control_normal_depth_train_po_v1 import Trainer_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1
from src.pipelines.wan2_1_t2v_1_3b_control_normal_depth_train_v1 import WanTrainingModule_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1
from src.trainers.wan2_1_t2v_1_3b_control_normal_depth_train_po_v2 import ModelCheckpointCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2,TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2
from src.trainers.wan2_1_t2v_1_3b_control_normal_depth_train_po_v2 import Trainer_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2
from src.pipelines.wan2_1_t2v_1_3b_control_normal_depth_train_v2 import WanTrainingModule_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2
from src.trainers.wan2_1_t2v_1_3b_control_normal_depth_train_po_v3 import ModelCheckpointCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3,TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3
from src.trainers.wan2_1_t2v_1_3b_control_normal_depth_train_po_v3 import Trainer_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3
from src.pipelines.wan2_1_t2v_1_3b_control_normal_depth_train_v3 import WanTrainingModule_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3
from src.trainers.wan2_1_t2v_1_3b_control_pointmap_train_po_v0 import ModelCheckpointCallback_wan2_1_t2v_1_3b_control_pointmap_train_po_v0,TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_pointmap_train_po_v0
from src.trainers.wan2_1_t2v_1_3b_control_pointmap_train_po_v0 import Trainer_wan2_1_t2v_1_3b_control_pointmap_train_po_v0
from src.pipelines.wan2_1_t2v_1_3b_control_pointmap_train_v0 import WanTrainingModule_wan2_1_t2v_1_3b_control_pointmap_train_po_v0
from src.trainers.wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0 import ModelCheckpointCallback_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0,TensorboardLoggingCallback_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0
from src.trainers.wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0 import Trainer_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0
from src.pipelines.wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0 import WanTrainingModule_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0
from src.trainers.wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1
from src.trainers.wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1 import Trainer_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1
from src.pipelines.wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1 import WanTrainingModule_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1
from src.trainers.wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0
from src.trainers.wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0 import Trainer_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0
from src.pipelines.wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0 import WanTrainingModule_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0
from src.trainers.wan2_1_fun_1_3b_control_normal_lora_image_train_v0 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_lora_image_train_v0,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_lora_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_normal_lora_image_train_v0 import Trainer_wan2_1_fun_1_3b_control_normal_lora_image_train_v0
from src.pipelines.wan2_1_fun_1_3b_control_normal_lora_image_train_v0 import WanTrainingModule_wan2_1_fun_1_3b_control_normal_lora_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_albedo_lora_image_train_v0 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_albedo_lora_image_train_v0 import Trainer_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0
from src.pipelines.wan2_1_fun_1_3b_control_albedo_lora_image_train_v0 import WanTrainingModule_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_depth_lora_image_train_v0 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_depth_lora_image_train_v0,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_depth_lora_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_depth_lora_image_train_v0 import Trainer_wan2_1_fun_1_3b_control_depth_lora_image_train_v0
from src.pipelines.wan2_1_fun_1_3b_control_depth_lora_image_train_v0 import WanTrainingModule_wan2_1_fun_1_3b_control_depth_lora_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_material_lora_image_train_v0 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_material_lora_image_train_v0,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_material_lora_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_material_lora_image_train_v0 import Trainer_wan2_1_fun_1_3b_control_material_lora_image_train_v0
from src.pipelines.wan2_1_fun_1_3b_control_material_lora_image_train_v0 import WanTrainingModule_wan2_1_fun_1_3b_control_material_lora_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0 import Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0
from src.pipelines.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0 import WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1
from src.trainers.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1 import Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1
from src.pipelines.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1 import WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1
from src.trainers.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2
from src.trainers.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2 import Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2
from src.pipelines.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2 import WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2
from src.trainers.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3
from src.trainers.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3 import Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3
from src.pipelines.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3 import WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3
from src.trainers.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4
from src.trainers.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4 import Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4
from src.pipelines.wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4 import WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4
from src.trainers.wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0 import Trainer_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0
from src.pipelines.wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0 import WanTrainingModule_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0 import Trainer_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0
from src.pipelines.wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0 import WanTrainingModule_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0 import ModelCheckpointCallback_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0,TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0
from src.trainers.wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0 import Trainer_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0
from src.pipelines.wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0 import WanTrainingModule_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0 import ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0,TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0 import Trainer_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0 import ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0,TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0 import Trainer_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0 import ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0,TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0 import Trainer_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0 import ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0,TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0 import Trainer_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_wo_dm_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_wo_dm_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_wo_prompt_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_wo_prompt_train_v0
from src.pipelines.wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v1 import WanTrainingModule_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v1
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0 import ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0,TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0 import Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_lora_video_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_lora_video_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0 import ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0,TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0 import Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0 import ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0,TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0
from src.trainers.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0 import Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_lora_image_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_lora_image_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_lora_image_train_v1 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_lora_image_train_v1
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_diffusion_forcing_lora_image_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_diffusion_forcing_lora_image_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_diffusion_forcing_wo_qk_lora_lora_image_train_v0 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_diffusion_forcing_wo_qk_lora_lora_image_train_v0
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1
from src.trainers.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1 import ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1,TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1
from src.trainers.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1 import Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_rec_loss_v0_lora_image_train_v1 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_rec_loss_v0_lora_image_train_v1
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_rec_loss_v1_lora_image_train_v1 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_rec_loss_v1_lora_image_train_v1
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_v0_lora_image_train_v1 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_v0_lora_image_train_v1
from src.pipelines.wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_v1_lora_image_train_v1 import WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_v1_lora_image_train_v1
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1
from src.trainers.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1 import ModelCheckpointCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1,TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1
from src.trainers.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1 import Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_lora_video_train_v1 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_lora_video_train_v1
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v1 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v1
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v2 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v2
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v3 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v3
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_save_prompt_embedding_v2 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_save_prompt_embedding_v2
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v4 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v4
from src.trainers.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4 import ModelCheckpointCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4,TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4
from src.trainers.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4 import Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v5 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v5
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_relight_debug_lora_video_train_v1 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_relight_debug_lora_video_train_v1
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_image_ablation_fft_train_v2 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_image_ablation_fft_train_v2
from src.trainers.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1 import ModelCheckpointCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1,TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1
from src.trainers.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1 import Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1
from src.pipelines.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1 import WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1
from src.trainers.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1 import ModelCheckpointCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1,TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1
from src.trainers.wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1 import Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v1 import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v1
from src.trainers.wan2_1_14b_t2v_matte_lora_image_train_v1 import ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_image_train_v1,TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_image_train_v1
from src.trainers.wan2_1_14b_t2v_matte_lora_image_train_v1 import Trainer_wan2_1_14b_t2v_matte_lora_image_train_v1
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v2 import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v2
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v1 import ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v1,TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v1
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v1 import Trainer_wan2_1_14b_t2v_matte_lora_video_train_v1
from src.pipelines.wan2_1_14b_t2v_nvs_lora_train_v1 import WanTrainingModule_wan2_1_14b_t2v_nvs_lora_train_v1
from src.trainers.wan2_1_14b_t2v_nvs_lora_video_train_v1 import ModelCheckpointCallback_wan2_1_14b_t2v_nvs_lora_video_train_v1,TensorboardLoggingCallback_wan2_1_14b_t2v_nvs_lora_video_train_v1
from src.trainers.wan2_1_14b_t2v_nvs_lora_video_train_v1 import Trainer_wan2_1_14b_t2v_nvs_lora_video_train_v1
from src.trainers.wan2_1_14b_t2v_nvs_lora_image_train_v1 import ModelCheckpointCallback_wan2_1_14b_t2v_nvs_lora_image_train_v1,TensorboardLoggingCallback_wan2_1_14b_t2v_nvs_lora_image_train_v1
from src.trainers.wan2_1_14b_t2v_nvs_lora_image_train_v1 import Trainer_wan2_1_14b_t2v_nvs_lora_image_train_v1
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v3 import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v3
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v2 import ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v2,TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v2
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v2 import Trainer_wan2_1_14b_t2v_matte_lora_video_train_v2
from src.pipelines.wan2_1_14b_t2v_flare_removal_lora_train_v1 import WanTrainingModule_wan2_1_14b_t2v_flare_removal_lora_train_v1
from src.trainers.wan2_1_14b_t2v_flare_removal_lora_video_train_v1 import ModelCheckpointCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v1,TensorboardLoggingCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v1
from src.trainers.wan2_1_14b_t2v_flare_removal_lora_video_train_v1 import Trainer_wan2_1_14b_t2v_flare_removal_lora_video_train_v1
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v4 import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v4
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v3 import ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v3,TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v3
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v3 import Trainer_wan2_1_14b_t2v_matte_lora_video_train_v3
from src.pipelines.wan2_1_14b_t2v_flare_removal_lora_train_v2 import WanTrainingModule_wan2_1_14b_t2v_flare_removal_lora_train_v2
from src.trainers.wan2_1_14b_t2v_flare_removal_lora_video_train_v2 import ModelCheckpointCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v2,TensorboardLoggingCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v2
from src.trainers.wan2_1_14b_t2v_flare_removal_lora_video_train_v2 import Trainer_wan2_1_14b_t2v_flare_removal_lora_video_train_v2
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v5 import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v5
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v4 import ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v4,TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v4
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v4 import Trainer_wan2_1_14b_t2v_matte_lora_video_train_v4
from src.pipelines.wan2_1_14b_t2v_flare_removal_lora_train_v3 import WanTrainingModule_wan2_1_14b_t2v_flare_removal_lora_train_v3
from src.trainers.wan2_1_14b_t2v_flare_removal_lora_video_train_v3 import ModelCheckpointCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v3,TensorboardLoggingCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v3
from src.trainers.wan2_1_14b_t2v_flare_removal_lora_video_train_v3 import Trainer_wan2_1_14b_t2v_flare_removal_lora_video_train_v3
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v6 import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v6
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v5 import ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v5,TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v5
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v5 import Trainer_wan2_1_14b_t2v_matte_lora_video_train_v5
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v7 import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v7
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v6 import ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v6,TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v6
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v6 import Trainer_wan2_1_14b_t2v_matte_lora_video_train_v6
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v6_single_lora import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v6_single_lora
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v6_ablation_single_lora import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v6_ablation_single_lora
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v8 import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v8
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v7 import ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v7,TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v7
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v7 import Trainer_wan2_1_14b_t2v_matte_lora_video_train_v7
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v1 import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v1
from src.trainers.wan2_1_14b_t2v_pbr_lora_video_train_v1 import Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v1
from src.trainers.wan2_1_14b_t2v_pbr_lora_video_train_v1 import ModelCheckpointCallback_wan2_1_14b_t2v_pbr_lora_video_train_v1,TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v1
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v8_ablation_single_lora_modality_embedding import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v8_ablation_single_lora_modality_embedding
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_ablation1_framecat_single_lora_train_v1 import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_ablation1_framecat_single_lora_train_v1
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v2 import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v2
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v3 import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v3
from src.trainers.wan2_1_14b_t2v_pbr_lora_video_train_v3 import ModelCheckpointCallback_wan2_1_14b_t2v_pbr_lora_video_train_v3,TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v3
from src.trainers.wan2_1_14b_t2v_pbr_lora_video_train_v3 import Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v3
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v9 import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v9
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v9 import ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v9,TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v9
from src.trainers.wan2_1_14b_t2v_matte_lora_video_train_v9 import Trainer_wan2_1_14b_t2v_matte_lora_video_train_v9
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v4 import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v4
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v5 import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v5
from src.trainers.wan2_1_14b_t2v_pbr_lora_video_train_v6 import ModelCheckpointCallback_wan2_1_14b_t2v_pbr_lora_video_train_v6,TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v6
from src.trainers.wan2_1_14b_t2v_pbr_lora_video_train_v6 import Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v6
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v6 import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6
from src.trainers.wan2_1_14b_t2v_pbr_lora_video_train_v7 import ModelCheckpointCallback_wan2_1_14b_t2v_pbr_lora_video_train_v7,TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v7
from src.trainers.wan2_1_14b_t2v_pbr_lora_video_train_v7 import Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v7
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_decoupled import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_decoupled
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v8 import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v8
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v9_wo_decoupled import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v9_wo_decoupled
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_gated import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_gated
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v6_w_channel_concat import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_w_channel_concat
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v9_w_channel_concat import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v9_w_channel_concat
from src.pipelines.wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_attn import WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_attn   
from src.trainers.wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn  import ModelCheckpointCallback_wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn,TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn
from src.trainers.wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn import Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn
from src.pipelines.wan2_1_14b_t2v_matte_lora_train_v10 import WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v10
# --- 定义各类组件的注册表 ---

DATASET_REGISTRY = {
    'PointOdyssey': PointOdysseyDataset_P1,
    'PointOdyssey_pointmap': PointOdysseyDataset_P2,
    'PointOdyssey_P3': PointOdysseyDataset_P3,
    'PointOdyssey_normal_relative_depth': PointOdysseyDataset_P4,
    'VideoDataset': VideoDataset,
    'PrimitivesDataset_v0': PrimitivesDataset_v0,
    'PrimitivesDataset_v1': PrimitivesDataset_v1,
    'PrimitivesDataset_v1_Caption': PrimitivesDataset_v1_Caption,
    # "Interiorverse": Interiorverse,
    "InteriorverseSingleFrame": InteriorverseSingleFrame,
    "InteriorverseSingleFrame_Caption": InteriorverseSingleFrame_Caption,
    "InteriorverseSingleFrame_Caption_Tonemap_Only_From_Embedding": InteriorverseSingleFrame_Caption_Tonemap_Only_From_Embedding,
    "InteriorverseSingleFrame_Tonemap": InteriorverseSingleFrame_Tonemap,
    "InteriorverseSingleFrame_Caption_Tonemap": InteriorverseSingleFrame_Caption_Tonemap,
    "InTheWildVideoDataset": InTheWildVideoDataset,
    "InTheWildIntrinsixDataset": InTheWildIntrinsixDataset,
    "InTheWildIntrinsixDataset_v1": InTheWildIntrinsixDataset_v1,
    "PSMix": PSMix,
    "PSVerse": PSVerse,
    "IBIMSDataset": IBIMSDataset,
    "NYU2Dataset": NYU2Dataset,
    "SintelDataset": SintelDataset,
    "ScanNetDataset": ScanNetDataset,
    "VideoMatte240KDataset": VideoMatte240KDataset,
    "MultiScene360Dataset": MultiScene360Dataset,
    "OpenHumanVidFlareDataset": OpenHumanVidFlareDataset,
    "VideoMatte240KTestDataset": VideoMatte240KTestDataset,
    "VideoMatte240KDataset_v2": VideoMatte240KDataset_v2,
    "FlareVideoDataset": FlareVideoDataset,
    "OpenHumanVidFlareEval": OpenHumanVidFlareEval,
    "MatteFootageDataset": MatteFootageDataset,
    "VideoMatte240KDataset_inference_background_generation": VideoMatte240KDataset_inference_background_generation,
    "OurPBRData": OurPBRData,
    "OurPBRData_Crop": OurPBRData_Crop,
    "SintelDataset_Crop": SintelDataset_Crop,
    "SintelDataset_Debug": SintelDataset_Debug,
    "InteriorverseSingleFrame_Caption_Tonemap_Inference": InteriorverseSingleFrame_Caption_Tonemap_Inference,
    "InteriorverseSingleFrame_Caption_Tonemap_Train": InteriorverseSingleFrame_Caption_Tonemap_Train,
    "HypersimDataset_Clean": HypersimDataset_Clean,
    "Interiorverse_Caption_Tonemap_Train_New": Interiorverse_Caption_Tonemap_Train_New,
    "OurPBRData_Crop_Eval": OurPBRData_Crop_Eval,
    "HypersimDataset_Test": HypersimDataset_Test,
    "HypersimDataset_Test_Clean": HypersimDataset_Test_Clean,
    "YoutubeMatteTestDataset": YoutubeMatteTestDataset,
    "OurPBRData_New": OurPBRData_New,
    "InTheWildVideoDataset_For_PBR": InTheWildVideoDataset_For_PBR,
    "InTheWildImageDataset_For_PBR": InTheWildImageDataset_For_PBR,
    "OurPBRData_Crop_Eval_For_Demo": OurPBRData_Crop_Eval_For_Demo,
}
# Only register HypersimDataset if it's available (h5py installed)
if HypersimDataset is not None:
    DATASET_REGISTRY["HypersimDataset"] = HypersimDataset

MODEL_REGISTRY = {
    'WanTrainingModule_IR_depth_normal_v0': WanTrainingModule_IR_depth_normal_v0,
    'WanTrainingModule_wan2_1_fun_14b_control_normal_lora_train_po_v0': WanTrainingModule_wan2_1_fun_14b_control_normal_lora_train_po_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_normal_lora_train_po_v0': WanTrainingModule_wan2_1_fun_1_3b_control_normal_lora_train_po_v0,
    'WanTrainingModule_wan2_1_t2v_1_3b_control_normal_train_po_v0': WanTrainingModule_wan2_1_t2v_1_3b_control_normal_train_po_v0,
    'WanTrainingModule_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0': WanTrainingModule_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0,
    'WanTrainingModule_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1': WanTrainingModule_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1,
    'WanTrainingModule_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2': WanTrainingModule_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2,
    'WanTrainingModule_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3': WanTrainingModule_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3,
    'WanTrainingModule_wan2_1_t2v_1_3b_control_pointmap_train_po_v0': WanTrainingModule_wan2_1_t2v_1_3b_control_pointmap_train_po_v0,
    'WanTrainingModule_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0': WanTrainingModule_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0,
    #'WanTrainingModule_wan2_2_ti2v_5b_normal_depth_train_v0': WanTrainingModule_wan2_2_ti2v_5b_normal_depth_train_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0': WanTrainingModule_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1': WanTrainingModule_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1,
    'WanTrainingModule_wan2_1_fun_1_3b_control_normal_lora_image_train_v0': WanTrainingModule_wan2_1_fun_1_3b_control_normal_lora_image_train_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0': WanTrainingModule_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_depth_lora_image_train_v0': WanTrainingModule_wan2_1_fun_1_3b_control_depth_lora_image_train_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_material_lora_image_train_v0': WanTrainingModule_wan2_1_fun_1_3b_control_material_lora_image_train_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0': WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1': WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1,
    'WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2': WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2,
    'WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3': WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3,
    'WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4': WanTrainingModule_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4,
    'WanTrainingModule_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0': WanTrainingModule_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0': WanTrainingModule_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0': WanTrainingModule_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_wo_dm_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_wo_dm_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_wo_prompt_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_wo_prompt_train_v0,
    'WanTrainingModule_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v1': WanTrainingModule_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v1,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_lora_video_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_lora_video_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_lora_image_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_lora_image_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_lora_image_train_v1': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_lora_image_train_v1,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_diffusion_forcing_lora_image_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_diffusion_forcing_lora_image_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_diffusion_forcing_wo_qk_lora_lora_image_train_v0': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_diffusion_forcing_wo_qk_lora_lora_image_train_v0,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_rec_loss_v0_lora_image_train_v1': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_rec_loss_v0_lora_image_train_v1,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_rec_loss_v1_lora_image_train_v1': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_rec_loss_v1_lora_image_train_v1,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_v0_lora_image_train_v1': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_v0_lora_image_train_v1,
    'WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_v1_lora_image_train_v1': WanTrainingModule_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_render_loss_v1_lora_image_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_lora_video_train_v1': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_lora_video_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v1': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v2': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v2,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v3': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v3,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_save_prompt_embedding_v2': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_save_prompt_embedding_v2,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v4': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v4,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v5': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_video_train_v5,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_relight_debug_lora_video_train_v1': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_relight_debug_lora_video_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_image_ablation_fft_train_v2': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_rm_rgblora_render_loss_v1_lora_image_ablation_fft_train_v2,
    'WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1': WanTrainingModule_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v1': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v2': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v2,
    'WanTrainingModule_wan2_1_14b_t2v_nvs_lora_train_v1': WanTrainingModule_wan2_1_14b_t2v_nvs_lora_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v3': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v3,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v4': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v4,
    'WanTrainingModule_wan2_1_14b_t2v_flare_removal_lora_train_v1': WanTrainingModule_wan2_1_14b_t2v_flare_removal_lora_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_flare_removal_lora_train_v2': WanTrainingModule_wan2_1_14b_t2v_flare_removal_lora_train_v2,
    'WanTrainingModule_wan2_1_14b_t2v_flare_removal_lora_train_v3': WanTrainingModule_wan2_1_14b_t2v_flare_removal_lora_train_v3,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v5': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v5,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v6': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v6,   
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v7': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v7,   
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v6_single_lora': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v6_single_lora,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v6_ablation_single_lora': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v6_ablation_single_lora,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v8': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v8,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v1': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v8_ablation_single_lora_modality_embedding': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v8_ablation_single_lora_modality_embedding,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_ablation1_framecat_single_lora_train_v1': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_ablation1_framecat_single_lora_train_v1,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v2': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v2,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v3': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v3,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v9': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v9,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v4': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v4,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v5': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v5,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_decoupled': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_decoupled,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v8': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v8,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v9_wo_decoupled': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v9_wo_decoupled,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_gated': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_gated,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_w_channel_concat': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_w_channel_concat,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v9_w_channel_concat': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v9_w_channel_concat,
    'WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_attn': WanTrainingModule_wan2_1_14b_t2v_pbr_lora_video_train_v6_wo_attn,
    'WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v10': WanTrainingModule_wan2_1_14b_t2v_matte_lora_train_v10,
}

OPTIMIZER_REGISTRY = {
    'AdamW': AdamW,
}

SCHEDULER_REGISTRY = {
    'CosineAnnealingLR': CosineAnnealingLR,
}

CALLBACK_REGISTRY = {
    'ModelCheckpoint_IR_depth_normal_v0': ModelCheckpointCallback_IR_depth_normal_v0,
    'TensorboardLoggingCallback_IR_depth_normal_v0': TensorboardLoggingCallback_IR_depth_normal_v0,
    'ModelCheckpoint_wan2_1_fun_14b_control_normal_lora_train_po_v0': ModelCheckpointCallback_wan2_1_fun_14b_control_normal_lora_train_po_v0,
    'TensorboardLoggingCallback_wan2_1_fun_14b_control_normal_lora_train_po_v0': TensorboardLoggingCallback_wan2_1_fun_14b_control_normal_lora_train_po_v0,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_normal_lora_train_po_v0': ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_lora_train_po_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_lora_train_po_v0': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_lora_train_po_v0,
    'ModelCheckpoint_wan2_1_t2v_1_3b_control_normal_train_po_v0': ModelCheckpointCallback_wan2_1_t2v_1_3b_control_normal_train_po_v0,
    'TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_train_po_v0': TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_train_po_v0,
    'ModelCheckpoint_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0': ModelCheckpointCallback_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0,
    'TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0': TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0,
    'ModelCheckpoint_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1': ModelCheckpointCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1,
    'TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1': TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1,
    'ModelCheckpoint_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2': ModelCheckpointCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2,
    'TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2': TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2,
    'ModelCheckpoint_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3': ModelCheckpointCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3,
    'TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3': TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3,
    'ModelCheckpoint_wan2_1_t2v_1_3b_control_pointmap_train_po_v0': ModelCheckpointCallback_wan2_1_t2v_1_3b_control_pointmap_train_po_v0,
    'TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_pointmap_train_po_v0': TensorboardLoggingCallback_wan2_1_t2v_1_3b_control_pointmap_train_po_v0,
    'ModelCheckpoint_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0': ModelCheckpointCallback_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0': TensorboardLoggingCallback_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0': ModelCheckpointCallback_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1': ModelCheckpointCallback_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_normal_lora_image_train_v0': ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_lora_image_train_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_lora_image_train_v0': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_lora_image_train_v0,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0': ModelCheckpointCallback_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_depth_lora_image_train_v0': ModelCheckpointCallback_wan2_1_fun_1_3b_control_depth_lora_image_train_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_depth_lora_image_train_v0': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_depth_lora_image_train_v0,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_material_lora_image_train_v0': ModelCheckpointCallback_wan2_1_fun_1_3b_control_material_lora_image_train_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_material_lora_image_train_v0': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_material_lora_image_train_v0,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0': ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1': ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2': ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3': ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4': ModelCheckpointCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0': ModelCheckpointCallback_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0': ModelCheckpointCallback_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0,
    'ModelCheckpoint_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0': ModelCheckpointCallback_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0,
    'TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0': TensorboardLoggingCallback_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0,
    'ModelCheckpoint_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0': ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0,
    'TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0': TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0,
    'ModelCheckpoint_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0': ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0,
    'TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0': TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0,
    'ModelCheckpoint_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0': ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0,
    'TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0': TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0,
    'ModelCheckpoint_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0': ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0,
    'TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0': TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0,
    'ModelCheckpoint_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0': ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0,
    'TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0': TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0,
    'ModelCheckpoint_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0': ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0,
    'TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0': TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0,
    'ModelCheckpoint_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0': ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0,
    'TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0': TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0,
    'ModelCheckpoint_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1': ModelCheckpointCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1,
    'TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1': TensorboardLoggingCallback_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1,
    'ModelCheckpoint_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1': ModelCheckpointCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1': TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1,
    'ModelCheckpoint_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4': ModelCheckpointCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4': TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4,
    'ModelCheckpoint_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1': ModelCheckpointCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1': TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1': TensorboardLoggingCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1,
    'ModelCheckpoint_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1': ModelCheckpointCallback_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1,
    'ModelCheckpoint_wan2_1_14b_t2v_matte_lora_image_train_v1': ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_image_train_v1,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_image_train_v1': TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_image_train_v1,
    'ModelCheckpoint_wan2_1_14b_t2v_matte_lora_video_train_v1': ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v1,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v1': TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v1,
    'ModelCheckpoint_wan2_1_14b_t2v_nvs_lora_video_train_v1': ModelCheckpointCallback_wan2_1_14b_t2v_nvs_lora_video_train_v1,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_nvs_lora_video_train_v1': TensorboardLoggingCallback_wan2_1_14b_t2v_nvs_lora_video_train_v1,
    'ModelCheckpoint_wan2_1_14b_t2v_nvs_lora_image_train_v1': ModelCheckpointCallback_wan2_1_14b_t2v_nvs_lora_image_train_v1,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_nvs_lora_image_train_v1': TensorboardLoggingCallback_wan2_1_14b_t2v_nvs_lora_image_train_v1,
    'ModelCheckpoint_wan2_1_14b_t2v_matte_lora_video_train_v2': ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v2,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v2': TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v2,
    'ModelCheckpoint_wan2_1_14b_t2v_flare_removal_lora_video_train_v1': ModelCheckpointCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v1,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v1': TensorboardLoggingCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v1,
    'ModelCheckpoint_wan2_1_14b_t2v_matte_lora_video_train_v3': ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v3,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v3': TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v3,
    'ModelCheckpoint_wan2_1_14b_t2v_flare_removal_lora_video_train_v2': ModelCheckpointCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v2,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v2': TensorboardLoggingCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v2,
    'ModelCheckpoint_wan2_1_14b_t2v_flare_removal_lora_video_train_v3': ModelCheckpointCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v3,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v3': TensorboardLoggingCallback_wan2_1_14b_t2v_flare_removal_lora_video_train_v3,
    'ModelCheckpoint_wan2_1_14b_t2v_matte_lora_video_train_v4': ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v4,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v4': TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v4,
    'ModelCheckpoint_wan2_1_14b_t2v_matte_lora_video_train_v5': ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v5,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v5': TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v5,
    'ModelCheckpoint_wan2_1_14b_t2v_matte_lora_video_train_v6': ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v6,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v6': TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v6,
    'ModelCheckpoint_wan2_1_14b_t2v_matte_lora_video_train_v7': ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v7,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v7': TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v7,
    'ModelCheckpoint_wan2_1_14b_t2v_pbr_lora_video_train_v1': ModelCheckpointCallback_wan2_1_14b_t2v_pbr_lora_video_train_v1,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v1': TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v1,
    'ModelCheckpoint_wan2_1_14b_t2v_pbr_lora_video_train_v3': ModelCheckpointCallback_wan2_1_14b_t2v_pbr_lora_video_train_v3,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v3': TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v3,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v9': TensorboardLoggingCallback_wan2_1_14b_t2v_matte_lora_video_train_v9,
    'ModelCheckpoint_wan2_1_14b_t2v_matte_lora_video_train_v9': ModelCheckpointCallback_wan2_1_14b_t2v_matte_lora_video_train_v9,
    'ModelCheckpoint_wan2_1_14b_t2v_pbr_lora_video_train_v6': ModelCheckpointCallback_wan2_1_14b_t2v_pbr_lora_video_train_v6,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v6': TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v6,
    'ModelCheckpoint_wan2_1_14b_t2v_pbr_lora_video_train_v7': ModelCheckpointCallback_wan2_1_14b_t2v_pbr_lora_video_train_v7,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v7': TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v7,
    'ModelCheckpoint_wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn': ModelCheckpointCallback_wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn,
    'TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn': TensorboardLoggingCallback_wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn,
}   



TRAINER_REGISTRY = {
    'Trainer_wan2_1_fun_14b_control_normal_lora_train_po_v0': Trainer_wan2_1_fun_14b_control_normal_lora_train_po_v0,
    'Trainer_wan2_1_fun_1_3b_control_normal_lora_train_po_v0': Trainer_wan2_1_fun_1_3b_control_normal_lora_train_po_v0,
    'Trainer_wan2_1_t2v_1_3b_control_normal_train_po_v0': Trainer_wan2_1_t2v_1_3b_control_normal_train_po_v0,
    'Trainer_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0': Trainer_wan2_1_t2v_1_3b_control_normal_lora_train_po_v0,
    'Trainer_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1': Trainer_wan2_1_t2v_1_3b_control_normal_depth_train_po_v1,
    'Trainer_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2': Trainer_wan2_1_t2v_1_3b_control_normal_depth_train_po_v2,
    'Trainer_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3': Trainer_wan2_1_t2v_1_3b_control_normal_depth_train_po_v3,
    'Trainer_wan2_1_t2v_1_3b_control_pointmap_train_po_v0': Trainer_wan2_1_t2v_1_3b_control_pointmap_train_po_v0,
    'Trainer_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0': Trainer_wan2_1_fun_1_1_1_3b_control_normal_depth_train_v0,
    #'Trainer_wan2_2_ti2v_5b_normal_depth_train_v0': Trainer_wan2_2_ti2v_5b_normal_depth_train_v0,
    'Trainer_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0': Trainer_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v0,
    'Trainer_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1': Trainer_wan2_1_fun_1_3b_control_mixed_modality_serial_train_v1,
    'Trainer_wan2_1_fun_1_3b_control_normal_lora_image_train_v0': Trainer_wan2_1_fun_1_3b_control_normal_lora_image_train_v0,
    'Trainer_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0': Trainer_wan2_1_fun_1_3b_control_albedo_lora_image_train_v0,
    'Trainer_wan2_1_fun_1_3b_control_depth_lora_image_train_v0': Trainer_wan2_1_fun_1_3b_control_depth_lora_image_train_v0,
    'Trainer_wan2_1_fun_1_3b_control_material_lora_image_train_v0': Trainer_wan2_1_fun_1_3b_control_material_lora_image_train_v0,
    'Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0': Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v0,
    'Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1': Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v1,
    'Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2': Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v2,
    'Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3': Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v3,
    'Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4': Trainer_wan2_1_fun_1_3b_control_normal_depth_wonder3d_image_train_v4,
    'Trainer_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0': Trainer_wan2_1_fun_1_3b_control_albedo_depth_material_normal_wonder3d_image_train_v0,
    'Trainer_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0': Trainer_wan2_1_fun_1_3b_control_albedo_material_normal_wonder3d_image_train_v0,
    'Trainer_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0': Trainer_wan2_1_fun_1_3b_control_albedo_material_normal_wo_self_attn_image_train_v0,
    'Trainer_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0': Trainer_wan2_1_1_3b_t2v_pbrgen_albedo_lora_video_train_v0,
    'Trainer_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0': Trainer_wan2_1_1_3b_t2v_pbrgen_normal_lora_video_train_v0,
    'Trainer_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0': Trainer_wan2_1_1_3b_t2v_pbrgen_material_lora_video_train_v0,
    'Trainer_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0': Trainer_wan2_1_1_3b_t2v_pbrgen_albedo_material_normal_lora_video_train_v0,
    'Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0': Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_alignment_lora_video_train_v0,
    'Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0': Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_lora_image_train_v0,
    'Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0': Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v0,
    'Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1': Trainer_wan2_1_1_3b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1,
    'Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1': Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v1,
    'Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4': Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_video_train_v4,
    'Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1': Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_train_v1,
    'Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1': Trainer_wan2_1_14b_t2v_pbrgen_pbr_sft_rec_gen_lora_image_prism_train_v1,
    'Trainer_wan2_1_14b_t2v_matte_lora_image_train_v1': Trainer_wan2_1_14b_t2v_matte_lora_image_train_v1,
    'Trainer_wan2_1_14b_t2v_matte_lora_video_train_v1': Trainer_wan2_1_14b_t2v_matte_lora_video_train_v1,
    'Trainer_wan2_1_14b_t2v_nvs_lora_video_train_v1': Trainer_wan2_1_14b_t2v_nvs_lora_video_train_v1,
    'Trainer_wan2_1_14b_t2v_nvs_lora_image_train_v1': Trainer_wan2_1_14b_t2v_nvs_lora_image_train_v1,
    'Trainer_wan2_1_14b_t2v_matte_lora_video_train_v2': Trainer_wan2_1_14b_t2v_matte_lora_video_train_v2,
    'Trainer_wan2_1_14b_t2v_flare_removal_lora_video_train_v1': Trainer_wan2_1_14b_t2v_flare_removal_lora_video_train_v1,
    'Trainer_wan2_1_14b_t2v_matte_lora_video_train_v3': Trainer_wan2_1_14b_t2v_matte_lora_video_train_v3,
    'Trainer_wan2_1_14b_t2v_flare_removal_lora_video_train_v2': Trainer_wan2_1_14b_t2v_flare_removal_lora_video_train_v2,
    'Trainer_wan2_1_14b_t2v_flare_removal_lora_video_train_v3': Trainer_wan2_1_14b_t2v_flare_removal_lora_video_train_v3,
    'Trainer_wan2_1_14b_t2v_matte_lora_video_train_v4': Trainer_wan2_1_14b_t2v_matte_lora_video_train_v4,
    'Trainer_wan2_1_14b_t2v_matte_lora_video_train_v5': Trainer_wan2_1_14b_t2v_matte_lora_video_train_v5,
    'Trainer_wan2_1_14b_t2v_matte_lora_video_train_v6': Trainer_wan2_1_14b_t2v_matte_lora_video_train_v6,
    'Trainer_wan2_1_14b_t2v_matte_lora_video_train_v7': Trainer_wan2_1_14b_t2v_matte_lora_video_train_v7,
    'Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v1': Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v1,
    'Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v3': Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v3,
    'Trainer_wan2_1_14b_t2v_matte_lora_video_train_v9': Trainer_wan2_1_14b_t2v_matte_lora_video_train_v9,
    'Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v6': Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v6,
    'Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v7': Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v7,
    'Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn': Trainer_wan2_1_14b_t2v_pbr_lora_video_train_v7_wo_attn,
}

# 添加 UNIT_REGISTRY 定义
UNIT_REGISTRY = {
    # 这里可以添加各种 unit 类的注册
    # 例如: 'unit_name': UnitClass,
}